### PR TITLE
Explecite CandidKtTask task type extending SourceTask

### PR DESCRIPTION
**Pull request by tglaeser**
I'm proposing  to replace extension properties `didPath` and `genPath`  with a `sourceSets` property as commonly used by other Gradle plugins that operate on source files.

Herewith an extension configuration of
```
candid {
    sourceSets.main.candid.destinationDirectory.fileValue(project.file('build/output'))
    genPackage = 'tld.d.etc'
}
```
matches a files system layout of
```
/working/dir/
├── build
│   └── output
│       └── Greet
│           └── tld
│               └── d
│                   └── etc
│                       └── greet.did.kt
├── build.gradle
└── src
    └── main
        └── candid
            └── greet.did
```
Please see `CandidKtPluginSpecification` for more use cases (I'm still using Spock, the preferred testing framework by Gradle, but I can easily convert this to Kotlin if requested).
In this example, the naming of directory `Greet` and `greet.did.kt`  seems counter intuitive and I would like to discuss how the behavior of `CandidCodeGenerator` can be changed to maybe get rid of directory `Greet` and name the generated Kotlin source file `Greet.kt` instead. Please note that the example above does not depict the default layout, please see the tests on this.

I was unable to upgrade dependency `com.github.seniorjoinu:candid-kt` beyond version `0.1-rc7` as the latest Gradle version still forces Kotlin version `1.3` into the classpath which then resulted in error 
```
java.lang.NoSuchMethodError: kotlin.jvm.internal.PropertyReference1Impl.<init>(Ljava/lang/Class;Ljava/lang/String;Ljava/lang/String;I)V
	at senior.joinu.candid.idl.IDLGrammar.<clinit>(IDLParser.kt)
```
when running the tests against `com.github.seniorjoinu:candid-kt:0.1-rc23`.

### CODE REVIEW

**Review by seniorjoinu — APPROVED** [review]

**Comment by seniorjoinu** [comment]
Thank you for this brilliant job!

I'm an absolutely zero when it comes to gradle and all that groovy stuff. 

```
/working/dir/
├── build
│   └── output
│       └── Greet
│           └── tld
│               └── d
│                   └── etc
│                       └── greet.did.kt
├── build.gradle
└── src
    └── main
        └── candid
            └── greet.did
```
This is a very unrealistic layout for projects like this. 

The main idea of the plugin is to enable any kotlin project to generate a client code for IC and **add** it to it's source set (and use it).
Let's imagine some example. You are Android developer. You don't know anything about the IC and how it works. You just know some dapp-related practices like key management, transactions and async networking. You have a task: `develop an application following this design <figma-link> that should use IC as a backend`. Your blockchain-team gives you the instruction: 'ok, so you new, huh? ok, listen here. here we have our canister's github repo. you just pull the latest version and then from your app project you use candid-kt gradle plugin - it will generate you all needed code, that you can then use inside your app'. And that should be enough. You shouldn't copy any files from the IC-repo, you shouldn't embed the IC-repo inside your android app repo (or vice-versa). I mean, you could, but the plugin's design should encourage you to decouple stuff as much as possible.

So for the small team the correct layout would be something like this.
```
.
└── our great single-repo project/
    ├── backend/
    │   ├── canister1/
    │   ├── canister2/
    │   └── dfx.json
    ├── frontend/
    │   ├── node_modules/
    │   ├── src/
    │   └── package.json
    └── mobileapp/
        ├── src/
        └── build.gradle
```
And you should be able to target your gradle plugin inside the `mobileapp/` to automatically trigger build inside your `backend/`, then generate client code inside your main sourceset (e.g. `./mobileapp/src/main/com/example/generated/canister1/canister1.did.kt`) for each canister there are.

And for more mature team the filetree would look like
```
.
├── our-big-project-ic-backend-admin/
│   ├── canister1/
│   └── dfx.json
├── our-big-project-ic-backend-customer/
│   ├── canister2/
│   └── dfx.json
└── our-big-project-android-single-app/
    ├── src/
    └── build.gradle
```
And you should also be able to generate client code for canisters the same way.
In future this kind of decoupling would enable us to fetch `.did` files online and don't even bother pulling the git repo.

P.S. See how Web3J plugin works. https://github.com/web3j/web3j-gradle-plugin

**Comment by tglaeser** [comment]
The Web3J Gradle plugin follows the standard Gradle layout which was actually based on the Maven layout, so the production Solidity sources can be found at `$projectDir/src/main/solidity`. We do the same here, the default production Candid source location is `$projectDir/src/main/candid`. Similarly the production Kotlin source location would be `$projectDir/src/main/kotlin`.

Now, the proposed default location for generated production Kotlin sources from the Candid files is `$projectDir/build/generated/sources/candid/kotlin/main`. What we then can do, whenever the Gradle Kotlin plugin is applied to the same project, we would add this location to the Kotlin production source set and make sure that task `generateCandidKt` runs before the Kotlin compile tasks. The default layout would be:
```
our great single-repo project/
├── backend
│   ├── canister1
│   ├── canister2
│   └── dfx.json
├── frontend
│   ├── node_modules
│   ├── package.json
│   └── src
└── mobileapp
    ├── build
    │   └── generated
    │       └── sources
    │           └── candid
    │               └── kotlin
    │                   └── main
    ├── build.gradle
    └── src
        └── main
            ├── candid
            └── kotlin
```
This looks like a nice Gradle multi-project build, however if I understand you correctly than Gradle is only used to build the `mobileapp` project, projects `backend` and `frontend` are unlikely to be managed by Gradle, although this might be possible.

Question is, were will the `*.did` files reside? If `mobileapp` is a Gradle single-project build then one would probably have a copy of the same `*.did` files used by the other two projects under `src/main/candid`.

Thoughts/concerns?

**Comment by seniorjoinu** [comment]
At my day work we have a solidity contracts repository. It has a layout like this:
```
.
└── web3-project/
    ├── solidity-src/
    │   ├── contract1.sol
    │   └── contract2.sol
    ├── java-wrappers/
    │   └── build.gradle
    └── ts-wrappers/
        ├── package.json
        └── tsconfig.json
```

`solidity-src` dir only contains solidity contracts.
`java-wrappers` dir only contains a gradle script (with wrapper and stuff, but it is unrelated) with config like this

```
// can point anywhere
def solidityDir = Paths.get(project.rootDir.getAbsolutePath()).parent.resolve("solidity-src").toString()

web3j {
    generatedPackageName = 'com.example.contracts.generated'
    generatedFilesBaseDir = "${project.projectDir}${File.separator}src"
    includedContracts = []

    fileTree(solidityDir).visit { contract ->
        includedContracts << contract.file.name.replace(".sol", "")
    }
}
```

`ts-wrappers` contains some truffle and typechain configs which together do exactly the same as web3j plugin for `java-wrappers` dir.

This layout/configs combination provide us with an ability to work on our solidity project independently, push changes and (with proper CI) get fresh artifacts which then can be used by our client projects (mobile and frontend).

I see this plugin as a tool that can be easily tweaked to provide the exact same flexibility: to not be bound to any kind of standards or specs. Yes, it can have default behavior to make it simple for the beginners. Like you've proposed - if there is no config for candid-kt-plugin specified, it would expect your `.did` files to lay inside `/src/main/candid/com/example/canister.did` and would generate kotlin code (as you proposed) into `build/generated/sources/candid/kotlin/canister.did.kt`. But there should be a simple way to override this logic. 

So, my short proposal would be: let's keep it as flexible and as decoupled as we can.

**Comment by seniorjoinu** [comment]
> Now, the proposed default location for generated production Kotlin sources from the Candid files is $projectDir/build/generated/sources/candid/kotlin/main. What we then can do, whenever the Gradle Kotlin plugin is applied to the same project, we would add this location to the Kotlin production source set and make sure that task generateCandidKt runs before the Kotlin compile tasks. 

So, I have no concerns about this, as long as it can be overridden.

> Question is, were will the *.did files reside? If mobileapp is a Gradle single-project build then one would probably have a copy of the same *.did files used by the other two projects under src/main/candid.

And for this: it should be possible to specify any location for this data.

**Comment by tglaeser** [comment]
> So, my short proposal would be: let's keep it as flexible and as decoupled as we can.

> And for this: it should be possible to specify any location for this data.

Certainly; please have a look at the tests, it has examples for extending and reconfiguring the source set, we only want to default to the usual Gradle conventions.

A more detailed project layout example with a couple did files added:
```
our great single-repo project/
├── backend
│   ├── canister1
│   │   ├── hello
│   │   │   ├── hello.did
│   │   │   └── main.did
│   │   └── hello_assets
│   │       ├── assetstorage.did
│   │       └── hello_assets.did
│   ├── canister2
│   └── dfx.json
├── frontend
│   ├── node_modules
│   ├── package.json
│   └── src
└── mobileapp
    ├── build
    │   └── generated
    │       └── sources
    │           └── candid
    │               └── kotlin
    │                   └── main
    ├── build.gradle
    └── src
        └── main
            ├── candid
            │   └── crypto.did
            └── kotlin

```
File `build.gradle` indicates the Gradle project location. It would be configured as
```
plugins {
    id 'com.github.seniorjoinu.candid'
}
candid {
    sourceSets.main.candid.srcDir '../backend/canister1'
}
```
Essentially in addition to the default source location another one gets added. The resulting generated Kotlin source tree would be
```
our great single-repo project/
...
└── mobileapp
    ├── build
    │   └── generated
    │       └── sources
    │           └── candid
    │               └── kotlin
    │                   └── main
    │                       ├── Crypto.kt
    │                       ├── hello
    │                       │   ├── Hello.kt
    │                       │   └── Main.kt
    │                       └── helloassets
    │                           ├── Assetstorage.kt
    │                           └── HelloAssets.kt
...
```
Does this make sense? If yes, the behavior of `CandidCodeGenerator#generateFor` would need to be tweaked a little, I believe at the moment it would write a different tree.

**Comment by seniorjoinu** [comment]
@tglaeser Seems fine to me!

Looks like the build fails. Please, fix it and I'll merge.

**Comment by tglaeser** [comment]
> Looks like the build fails. Please, fix it and I'll merge.

Error is `Could not GET 'http://cache/org/jetbrains/kotlin/kotlin-reflect/1.4.10/kotlin-reflect-1.4.10.jar'`.

That's a strange URL; seems a JitPack configuration error.

I don't know much about JitPack, but it seems you have to tweak the build script in order for JitPack to properly work, which is something I would be hesitant to do.  I used Travis CI in the past; with it there is no need to make changes to the build descriptor, instead you would add a `.travis.yml` descriptor to the repository which in turn describes the CI behavior.

I believe you would need to setup CI as the repository is under your name. Thanks.

**Pull request merged**
